modules:
  - type: dnf
    repos:
      copr:
        - atim/starship
        - imput/helium
        - maveonair/jetbrains-mono-nerd-fonts
    install:
      install-weak-deps: false
      packages:
        # Terminal and shell
        - kitty
        - micro
        - starship
        - vim
        - nano
        - just

        # Environment
        - fzf
        - power-profiles-daemon
        - xorg-x11-server-Xwayland
        - headsetcontrol
        - mediainfo
        - polkit
        - xfce-polkit
        - fprintd-pam
        - xdg-user-dirs
        - dbus-tools
        - dbus-daemon
        - wl-clipboard
        - cliphist
        - pavucontrol
        - playerctl
        - qt5-qtwayland
        - qt6-qtwayland
        - vulkan-validation-layers
        - vulkan-tools
        - google-noto-emoji-fonts
        - gnome-disk-utility
        - ddcutil
        - openssl
        - alsa-firmware
        - distrobox
        - steam-devices

        # Audio
        - wireplumber
        - pipewire
        - pamixer
        - pulseaudio-utils

        # Networking
        - network-manager-applet
        - NetworkManager
        - NetworkManager-openvpn
        - NetworkManager-openvpn-gnome
        - NetworkManager-openconnect
        - NetworkManager-openconnect-gnome
        - bluez
        - bluez-tools
        - blueman
        - firewall-config

        # Browser
        - helium-bin

        # file manager
        - thunar
        - thunar-archive-plugin
        - thunar-volman
        - xarchiver
        - imv
        - p7zip
        - gvfs-mtp
        - gvfs-gphoto2
        - gvfs-smb
        - gvfs-nfs
        - gvfs-fuse
        - gvfs-archive
        - android-tools

        # screenshot
        - slurp
        - grim
        - swappy

        # display
        - wlr-randr
        - wlsunset
        - brightnessctl
        - kanshi

        # notifications
        - dunst

        # GUI
        - fontawesome-fonts-all
        - jetbrains-mono-nerd-fonts
        - jetbrains-mononl-nerd-fonts
        - gnome-icon-theme
        - paper-icon-theme
        - breeze-icon-theme
        - papirus-icon-theme
    remove:
      packages:
        - firefox
        - firefox-langpacks
