-- cvos Hyprland keybind defaults
-- Use the helper-style bind API expected by the Omarchy/Hyprland helper layer.

terminal = "kitty"
browser = "helium"
fileManager = "thunar"

hl.bind("SUPER, RETURN", "exec ${terminal}")
hl.bind("SUPER SHIFT, RETURN", "exec ${browser}")
hl.bind("SUPER SHIFT, F", "exec ${fileManager}")
hl.bind("SUPER SHIFT, B", "exec ${browser}")

hl.bind("SUPER, Q", "killactive")
hl.bind("SUPER, W", "killactive")
hl.bind("SUPER, F", "fullscreen 0")
hl.bind("SUPER ALT, F", "fullscreen 1")
hl.bind("SUPER, T", "togglefloating")
hl.bind("SUPER, J", "layoutmsg togglesplit")
hl.bind("SUPER, P", "pseudo")
hl.bind("SUPER, G", "togglegroup")
hl.bind("SUPER, S", "togglespecialworkspace scratchpad")
hl.bind("SUPER, grave", "togglespecialworkspace scratchpad")
hl.bind("SUPER ALT, S", "movetoworkspacesilent special:scratchpad")
hl.bind("SUPER SHIFT, grave", "movetoworkspacesilent special:scratchpad")

hl.bind("SUPER, left", "movefocus l")
hl.bind("SUPER, right", "movefocus r")
hl.bind("SUPER, up", "movefocus u")
hl.bind("SUPER, down", "movefocus d")
hl.bind("ALT, TAB", "cyclenext")
hl.bind("ALT SHIFT, TAB", "cyclenext prev")
hl.bind("CTRL ALT, TAB", "focusmonitor +1")
hl.bind("CTRL ALT SHIFT, TAB", "focusmonitor -1")

hl.bind("SUPER SHIFT, left", "swapwindow l")
hl.bind("SUPER SHIFT, right", "swapwindow r")
hl.bind("SUPER SHIFT, up", "swapwindow u")
hl.bind("SUPER SHIFT, down", "swapwindow d")

hl.bind("SUPER, code:10", "workspace 1")
hl.bind("SUPER, code:11", "workspace 2")
hl.bind("SUPER, code:12", "workspace 3")
hl.bind("SUPER, code:13", "workspace 4")
hl.bind("SUPER, code:14", "workspace 5")
hl.bind("SUPER, code:15", "workspace 6")
hl.bind("SUPER, code:16", "workspace 7")
hl.bind("SUPER, code:17", "workspace 8")
hl.bind("SUPER, code:18", "workspace 9")
hl.bind("SUPER, code:19", "workspace 10")
hl.bind("SUPER SHIFT, code:10", "movetoworkspace 1")
hl.bind("SUPER SHIFT, code:11", "movetoworkspace 2")
hl.bind("SUPER SHIFT, code:12", "movetoworkspace 3")
hl.bind("SUPER SHIFT, code:13", "movetoworkspace 4")
hl.bind("SUPER SHIFT, code:14", "movetoworkspace 5")
hl.bind("SUPER SHIFT, code:15", "movetoworkspace 6")
hl.bind("SUPER SHIFT, code:16", "movetoworkspace 7")
hl.bind("SUPER SHIFT, code:17", "movetoworkspace 8")
hl.bind("SUPER SHIFT, code:18", "movetoworkspace 9")
hl.bind("SUPER SHIFT, code:19", "movetoworkspace 10")
hl.bind("SUPER SHIFT ALT, code:10", "movetoworkspacesilent 1")
hl.bind("SUPER SHIFT ALT, code:11", "movetoworkspacesilent 2")
hl.bind("SUPER SHIFT ALT, code:12", "movetoworkspacesilent 3")
hl.bind("SUPER SHIFT ALT, code:13", "movetoworkspacesilent 4")
hl.bind("SUPER SHIFT ALT, code:14", "movetoworkspacesilent 5")
hl.bind("SUPER SHIFT ALT, code:15", "movetoworkspacesilent 6")
hl.bind("SUPER SHIFT ALT, code:16", "movetoworkspacesilent 7")
hl.bind("SUPER SHIFT ALT, code:17", "movetoworkspacesilent 8")
hl.bind("SUPER SHIFT ALT, code:18", "movetoworkspacesilent 9")
hl.bind("SUPER SHIFT ALT, code:19", "movetoworkspacesilent 10")
hl.bind("SUPER, TAB", "workspace e+1")
hl.bind("SUPER SHIFT, TAB", "workspace e-1")
hl.bind("SUPER CTRL, TAB", "workspace previous")
hl.bind("SUPER, mouse_down", "workspace e+1")
hl.bind("SUPER, mouse_up", "workspace e-1")
hl.bind("SUPER SHIFT ALT, left", "movecurrentworkspacetomonitor l")
hl.bind("SUPER SHIFT ALT, right", "movecurrentworkspacetomonitor r")
hl.bind("SUPER SHIFT ALT, up", "movecurrentworkspacetomonitor u")
hl.bind("SUPER SHIFT ALT, down", "movecurrentworkspacetomonitor d")

hl.bind("SUPER ALT, G", "moveoutofgroup")
hl.bind("SUPER ALT, left", "moveintogroup l")
hl.bind("SUPER ALT, right", "moveintogroup r")
hl.bind("SUPER ALT, up", "moveintogroup u")
hl.bind("SUPER ALT, down", "moveintogroup d")
hl.bind("SUPER ALT, TAB", "changegroupactive f")
hl.bind("SUPER ALT SHIFT, TAB", "changegroupactive b")
hl.bind("SUPER CTRL, left", "changegroupactive b")
hl.bind("SUPER CTRL, right", "changegroupactive f")

hl.bind("SUPER, code:20", "resizeactive -100 0")
hl.bind("SUPER, code:21", "resizeactive 100 0")
hl.bind("SUPER SHIFT, code:20", "resizeactive 0 -100")
hl.bind("SUPER SHIFT, code:21", "resizeactive 0 100")
hl.bind("SUPER ALT, code:20", "resizeactive -25 0")
hl.bind("SUPER ALT, code:21", "resizeactive 25 0")
hl.bind("SUPER SHIFT ALT, code:20", "resizeactive 0 -25")
hl.bind("SUPER SHIFT ALT, code:21", "resizeactive 0 25")
hl.bind("SUPER CTRL, code:20", "resizeactive -300 0")
hl.bind("SUPER CTRL, code:21", "resizeactive 300 0")
hl.bind("SUPER CTRL SHIFT, code:20", "resizeactive 0 -300")
hl.bind("SUPER CTRL SHIFT, code:21", "resizeactive 0 300")

hl.bind(", PRINT", "exec grim -g \"$(slurp)\" - | swappy -f -")
hl.bind("SUPER, PRINT", "exec pkill hyprpicker || hyprpicker -a")
hl.bind("SUPER CTRL, L", "exec hyprlock")

hl.bind("SUPER, mouse:272", "movewindow")
hl.bind("SUPER, mouse:273", "resizewindow")

hl.bind(", XF86AudioRaiseVolume", "exec pamixer -i 5")
hl.bind(", XF86AudioLowerVolume", "exec pamixer -d 5")
hl.bind(", XF86MonBrightnessUp", "exec brightnessctl set +5%")
hl.bind(", XF86MonBrightnessDown", "exec brightnessctl set 5%-")
hl.bind(", XF86AudioMute", "exec pamixer -t")
hl.bind(", XF86AudioPlay", "exec playerctl play-pause")
hl.bind(", XF86AudioNext", "exec playerctl next")
hl.bind(", XF86AudioPrev", "exec playerctl previous")
